### ISSUE TITLE
Paper: Software for urban planning practice 

### ISSUE THREAD

**Issue by d-wasserman** [APA-Technology-Division/urban-and-regional-planning-resources#62]
@lianplass - these are all good resources to add based on this paper? What do you think?
https://www.researchgate.net/publication/361221129_Free_and_open_source_urbanism_Software_for_urban_planning_practice
I could use help contributing these if anyone wants something to look at adding.

**Comment by lianplass** [comment]
Hello!  Agreed.  My only concern is about the duplicates and libraries that some might consider a little too specialized.  Was also thinking that it might be worthwhile to create a JS subheader in the repo if there isnt one already.  Quickly pulled and parsed the repo and ran a vlookup with the items listed in the article's table.  Not a fuzzy lookup so it will probably need a little cleaning, but it did ID some dupes to start. [Here's the spreadsheet](https://docs.google.com/spreadsheets/d/1mGwSveSTwyV8SBY8aBLxBaSH_bfVxtdJDs4i4i88rVg/edit?usp=sharing )

Let me know if there were any specific items you took exception to, otherwise I can put it on my list for this week.

**Comment by d-wasserman** [comment]
I am noticing that too. Like some libraries might be considered related or
sub categories of the others. I think we should avoid too many duplicates
or even sub-libraries.
David Wasserman
Email: ***@***.***
Cell: 407 325 6242

**Comment by d-wasserman** [comment]
Seems like the validation found a few duplicate links. Are we sure we don't have these yet?

**Comment by d-wasserman** [comment]
@lianplass - I am breaking up the contributions by category to simplify things. Merging was a little odd between the branches.

**Comment by lobosolo88** [comment]
No

**Comment by d-wasserman** [comment]
@lianplass - think we can close this for now?
